#!/bin/bash

# declare variable for storing path given as argument
path=$1
prefetcher=""

# check if path is given as argument
if [ "$path" = "context" ]
then
    prefetcher="ContextBasedPrefetcher"
elif [ "$path" = "stride" ]
then
    prefetcher="StridePrefetcher"
elif [ "$path" = "tagged" ]
then
    prefetcher="TaggedPrefetcher"
elif [ "$path" = "signature" ]
then
    prefetcher="SignaturePathPrefetcher"
elif [ "$path" = "indirect" ]
then
    prefetcher="IndirectMemoryPrefetcher"
else
    echo "Invalid argument"
    exit 1
fi

# read a file named home and store it in a variable
home=$(cat home)

build/X86/gem5.opt -d stats/bzip2/${path} \
configs/deprecated/example/se.py \
--cpu-type=DerivO3CPU --sys-clock=3GHz \
--caches --l1i_size=32kB --l1d_size=64kB \
--l2cache --l2_size=2MB --l2-hwp-type=${prefetcher} \
--mem-size=4GB --mem-type=DDR3_1600_8x8 -F 10000 -s 20000 -W 50000 -I 500000 \
-c ${home}/benchspec/CPU2006/401.bzip2/exe/bzip2_base.gcc43-64bit \
-o "${home}/benchspec/CPU2006/401.bzip2/data/ref/input/input.source 280"